import numpy as np
import partOneA as partOne
import matplotlib.pyplot as plt
import partTwoA as prt2a

def mat_square(data):
    for i in range(np.array(data).shape[0]):
        for j in range(np.array(data).shape[1]):
            data[i][j]=data[i][j]**2
    return data

if __name__=='__main__':
    tran_testX, tran_testY, tran_trainX, tran_trainY = prt2a.acquire_partTwodata();
    korder = 8
    squ_tranX = mat_square(tran_trainX)
    squ_testX = mat_square(tran_testX)
    trainX = np.concatenate((tran_trainX, squ_tranX), axis=1)
    testX = np.concatenate((tran_testX, squ_testX), axis=1)
    print(trainX.shape)
    print(testX.shape)
    tr_testY = tran_testY.reshape(len(tran_testY), 1)
    tr_trainY = tran_trainY.reshape(len(tran_trainY), 1)
    testY = np.concatenate((tr_testY, tr_testY), axis=0)
    trainY = np.concatenate((tr_trainY, tr_trainY), axis=0)
    LS_theta = partOne.least_squ_theta(trainX, trainY)
    print('testX', testX.shape)
    print('LS_theta', LS_theta.shape)
    LS_result = partOne.least_squ_predi(testX, LS_theta)
    LS_error = partOne.error(LS_result, testY)
    LS_mae_error = prt2a.mae_error(LS_result, testY)
    print('LS_result', LS_result.shape)
    print('LS_MSE_error:', LS_error)
    print('LS_MAE_error:', LS_mae_error)
    plt.figure(1)
    plt.title('least_squares(LS)')
    plt.xlabel('x-value')
    plt.ylabel('y-label')
    plt.plot(testX[0], LS_result, '.-')
    plt.plot(testX[0], testY, '.-')
    # plt.plot(trainX[0], trainY,'*')
    plt.legend(["test", "true"])
    # Regularized LS(RLS)
    RLS_theta = partOne.RLS_theta(trainX, trainY)
    RLS_result = partOne.RLS_predi(testX, RLS_theta)
    RLS_error = partOne.error(RLS_result, testY)
    RLS_mae_error = prt2a.mae_error(RLS_result, testY)
    print('RLS_MSE_error:', RLS_error)
    print('RLS_MAE_error:', RLS_mae_error)
    plt.figure(2)
    plt.title('Regularized LS(RLS)')
    plt.xlabel('x-value')
    plt.ylabel('y-label')
    plt.plot(testX[0], RLS_result, '.-')
    plt.plot(testX[0], testY, '.-')
    # plt.plot(trainX[0], trainY,'*')
    plt.legend(["test", "true"])
    # L1-regularized LS(LASSO)
    LASSO_theta = partOne.LASSO_Theta(trainX, trainY, 8)
    LASSO_result = partOne.LASSO_predi(testX, LASSO_theta)
    LASSO_error = partOne.error(LASSO_result, testY)
    LASSO_mae_error = prt2a.mae_error(LASSO_result, testY)
    print('LASSO_MSE_error:', LASSO_error)
    print('LASSO_MAE_error:', LASSO_mae_error)
    plt.figure(3)
    plt.title('L1-regularized LS(LASSO)')
    plt.xlabel('x-value')
    plt.ylabel('y-label')
    plt.plot(testX[0], LASSO_result, '.-')
    plt.plot(testX[0], testY, '.-')
    # plt.plot(trainX[0], trainY,'*')
    plt.legend(["test", "true"])
    # Robust regression(RR)
    RR_theta = partOne.RR_Theta(trainX[1], trainY, trainX, korder)
    # print(RR_theta.shape)
    RR_result = partOne.RR_predi(testX, RR_theta)
    RR_error = partOne.error(RR_result, testY)
    RR_mae_error = prt2a.mae_error(RR_result, testY)
    print('RR_MSE_error:', RR_error)
    print('RR_MAR_error:', RR_mae_error)
    plt.figure(4)
    plt.title('Robust regression(RR)')
    plt.xlabel('x-value')
    plt.ylabel('y-label')
    plt.plot(testX[0], RR_result, '.-')
    plt.plot(testX[0], testY, '.-')
    # plt.plot(trainX[0], trainY,'*')
    plt.legend(["test", "true"])
    # Bayesian regression (BR)
    BR_cov, BR_mean = partOne.posterior_BR(trainX, trainY)
    average, fangcha = partOne.BR_predi(testX, BR_cov, BR_mean)
    BR_polyy = np.random.normal(average, np.sqrt(np.abs(fangcha)), size=None)
    # print('average.shape:', average.shape)
    # print('fangcha.shape:', fangcha.shape)
    # print('BR_pred.shape:', BR_polyy.shape)
    BR_error = partOne.error(BR_polyy, testY)
    BR_mae_error = prt2a.mae_error(BR_polyy, testY)
    print('BR_MSE_error', BR_error)
    print('BR_MAE_error:', RR_mae_error)
    plt.figure(5)
    plt.title('Bayesian regression (BR)')
    plt.xlabel('x-value')
    plt.ylabel('y-label')
    plt.plot(testX[0], BR_polyy, '.-')
    plt.plot(testX[0], testY, '.-')
    # plt.plot(trainX[0], trainY, '*')
    plt.legend(["test", "true"])
    plt.show()